version: '3.8'

services:
  hubspot-service:
    build: 
      context: ./app
    restart: always
    container_name: hubspot-service
    expose:
      - "3000"
    ports:
      - "3000:3000"
    environment:
      - API_KEY=
      - PORT=
    networks:
      - axur-challenge-network
networks:
  axur-challenge-network:
    driver: bridge